version: "3.7"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "courier_db"
      POSTGRES_PASSWORD: "Password1!"
    ports:
      - "5432:5432"
    volumes:
      - .compose/postgres:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
